export const PRESET_FUNDS: PresetFund[] = [
  {
    displayName: "Madrona Venture Fund III, L.P. (2005) - 7.0x",
    fundName: "Madrona Venture Fund III, L.P.",
    vintage: 2005,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 5.0,
    grossReturnMultiple: 7.0,
    irr: 23.34,
  },
  {
    displayName: "Oregon Angel Fund 2008, LLC (2008) - 9.96x",
    fundName: "Oregon Angel Fund 2008, LLC",
    vintage: 2008,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 1.0,
    grossReturnMultiple: 9.96,
    irr: 20.88,
  },
  {
    displayName: "Oregon Angel Fund 2016, LLC (2016) - 6.95x",
    fundName: "Oregon Angel Fund 2016, LLC",
    vintage: 2016,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 1.5,
    grossReturnMultiple: 6.95,
    irr: 27.69,
  },
  {
    displayName: "FP Venture 2011 (2011) - 6.68x",
    fundName: "FP Venture 2011",
    vintage: 2011,
    strategy: "Venture Capital",
    source: "Oklahoma Teachers' Retirement System",
    sourceUrl: "OTRS Meketa Private Markets Interim Report (Q4 2024)",
    size: 20.0,
    grossReturnMultiple: 6.68,
    irr: 34.1,
  },
  {
    displayName: "Oregon Angel Fund 2015, LLC (2015) - 5.55x",
    fundName: "Oregon Angel Fund 2015, LLC",
    vintage: 2015,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 1.5,
    grossReturnMultiple: 5.55,
    irr: 19.62,
  },
  {
    displayName: "Sequoia Capital (Legacy Funds) (1999) - 5.44x",
    fundName: "Sequoia Capital (Legacy Funds)",
    vintage: 1999,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 96.6,
    grossReturnMultiple: 5.44,
    irr: 17.4,
  },
  {
    displayName: "GGV V (2014) - 5.0x",
    fundName: "GGV V",
    vintage: 2014,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 35.0,
    grossReturnMultiple: 5.0,
    irr: 24.2,
  },
  {
    displayName: "Sequoia Capital US Venture XVI (2018) - 4.55x",
    fundName: "Sequoia Capital US Venture XVI",
    vintage: 2018,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 2.0,
    grossReturnMultiple: 4.55,
    irr: 33.5,
  },
  {
    displayName: "Khosla Ventures IV (2011) - 4.07x",
    fundName: "Khosla Ventures IV",
    vintage: 2011,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 60.0,
    grossReturnMultiple: 4.07,
    irr: 22.0,
  },
  {
    displayName: "Oregon Angel Fund 2013, LLC (2013) - 3.82x",
    fundName: "Oregon Angel Fund 2013, LLC",
    vintage: 2013,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 1.5,
    grossReturnMultiple: 3.82,
    irr: 11.97,
  },
  {
    displayName: "Khosla Ventures Seed B (2012) - 3.55x",
    fundName: "Khosla Ventures Seed B",
    vintage: 2012,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 20.0,
    grossReturnMultiple: 3.55,
    irr: 18.0,
  },
  {
    displayName: "Seven Peaks Ventures Fund, L.P. (2014) - 3.51x",
    fundName: "Seven Peaks Ventures Fund, L.P.",
    vintage: 2014,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 0.5,
    grossReturnMultiple: 3.51,
    irr: 15.74,
  },
  {
    displayName: "FP Venture 2013 (2013) - 3.43x",
    fundName: "FP Venture 2013",
    vintage: 2013,
    strategy: "Venture Capital",
    source: "Oklahoma Teachers' Retirement System",
    sourceUrl: "OTRS Meketa Private Markets Interim Report (Q4 2024)",
    size: 20.0,
    grossReturnMultiple: 3.43,
    irr: 21.9,
  },
  {
    displayName: "Khosla Ventures V (2014) - 3.37x",
    fundName: "Khosla Ventures V",
    vintage: 2014,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 60.0,
    grossReturnMultiple: 3.37,
    irr: 19.9,
  },
  {
    displayName: "FP Venture 2012 (2012) - 3.29x",
    fundName: "FP Venture 2012",
    vintage: 2012,
    strategy: "Venture Capital",
    source: "Oklahoma Teachers' Retirement System",
    sourceUrl: "OTRS Meketa Private Markets Interim Report (Q4 2024)",
    size: 20.0,
    grossReturnMultiple: 3.29,
    irr: 19.3,
  },
  {
    displayName: "OVP Venture Partners VII, L.P. (2006) - 3.22x",
    fundName: "OVP Venture Partners VII, L.P.",
    vintage: 2006,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 7.0,
    grossReturnMultiple: 3.22,
    irr: 8.63,
  },
  {
    displayName: "FP Venture 2014 (2014) - 3.05x",
    fundName: "FP Venture 2014",
    vintage: 2014,
    strategy: "Venture Capital",
    source: "Oklahoma Teachers' Retirement System",
    sourceUrl: "OTRS Meketa Private Markets Interim Report (Q4 2024)",
    size: 20.0,
    grossReturnMultiple: 3.05,
    irr: 17.8,
  },
  {
    displayName: "FP Venture 2010 (2010) - 2.98x",
    fundName: "FP Venture 2010",
    vintage: 2010,
    strategy: "Venture Capital",
    source: "Oklahoma Teachers' Retirement System",
    sourceUrl: "OTRS Meketa Private Markets Interim Report (Q4 2024)",
    size: 20.0,
    grossReturnMultiple: 2.98,
    irr: 14.6,
  },
  {
    displayName: "Peak XV Partners India VI (2018) - 2.86x",
    fundName: "Peak XV Partners India VI",
    vintage: 2018,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 6.4,
    grossReturnMultiple: 2.86,
    irr: 21.0,
  },
  {
    displayName: "Founders' Co-op III, L.P. (2014) - 2.82x",
    fundName: "Founders' Co-op III, L.P.",
    vintage: 2014,
    strategy: "Venture Capital",
    source: "Oregon Growth Account",
    sourceUrl: "https://www.oregon.gov/biz/Publications/OGA/Performance%20Report/0325OGAPublicPerformanceReport.pdf",
    size: 2.5,
    grossReturnMultiple: 2.82,
    irr: 15.55,
  },
  {
    displayName: "Vertical Venture Partners (2015) - 2.68x",
    fundName: "Vertical Venture Partners",
    vintage: 2015,
    strategy: "Venture/Growth",
    source: "UC Regents",
    sourceUrl: "UC Regents Private Equity Investments disclosure (as of June 30, 2025)",
    size: 5.0,
    grossReturnMultiple: 2.68,
    irr: 27.2,
  },
];
