import {useEffect,useRef,useState} from 'react';
import {Button} from './Button';
import {Box,Footprints,Layers,ArrowUpRight,Download,ImageIcon,X,Play,Pause} from 'lucide-react';
import {createHouseViewer,rooms,type HouseViewer} from './model';
export default function HousePage(){
 const mount=useRef<HTMLDivElement>(null),viewer=useRef<HouseViewer|null>(null);
 const [level,setLevel]=useState(0),[mode,setMode]=useState('dollhouse'),[selected,setSelected]=useState('living'),[panel,setPanel]=useState(false),[tour,setTour]=useState(false),[error,setError]=useState('');
 useEffect(()=>{try{viewer.current=createHouseViewer(mount.current!);}catch{setError('The 3D view needs WebGL. Try a browser with hardware acceleration enabled.');}return()=>viewer.current?.dispose();},[]);
 function enter(id:string){setSelected(id);setMode('walk');viewer.current?.visit(id);}
 function overview(){setMode('dollhouse');setTour(false);viewer.current?.overview();}
 function changeLevel(i:number){setLevel(i);setMode('dollhouse');setTour(false);viewer.current?.setLevel(i);}
 useEffect(()=>{if(!tour)return;const stops=rooms.filter(r=>r.level===level);let i=0;enter(stops[0].id);const timer=setInterval(()=>{i=(i+1)%stops.length;enter(stops[i].id);},6500);return()=>clearInterval(timer);},[tour,level]);
 return <main className="house-app"><header className="topbar"><div className="brand"><Box/><div><h1>716 Douglass</h1><p>A home, in three dimensions</p></div></div><span className="revision">● Appraisal-based · first model</span><Button variant="outline" onClick={async()=>{try{await viewer.current?.download();}catch{setError('Export failed. Please try again.');}}}><Download/><span>Export for Blender</span></Button></header>
 <section className="workspace"><div ref={mount} className="viewport" aria-label="Interactive 3D house model"/><div className="toolbar"><div className="segmented"><Button variant={mode==='dollhouse'?'default':'ghost'} onClick={overview}><Box/>Dollhouse</Button><Button variant={mode==='walk'?'default':'ghost'} onClick={()=>{setTour(false);enter(level?'lower-living':'living');}}><Footprints/>Walk inside</Button></div><Button variant="outline" onClick={()=>setTour(!tour)}>{tour?<Pause/>:<Play/>}{tour?'Pause tour':'Guided tour'}</Button></div>
 <aside className="level-card"><p className="eyebrow">EXPLORE THE HOUSE</p><h2>Welcome home.</h2><p className="intro">Two levels. Familiar spaces.<br/>A new way to look around.</p><div className="levels">{['Main level','Lower level'].map((name,i)=><Button key={name} variant={level===i?'default':'ghost'} onClick={()=>changeLevel(i)}><Layers/><span>{name}<small>Unit {i+1} · {i?'822':'1,244'} sq ft</small></span></Button>)}</div><p className="eyebrow room-heading">JUMP TO A ROOM</p><nav aria-label="Rooms">{rooms.filter(r=>r.level===level).map((r,i)=><Button key={r.id} variant="ghost" className={'room '+(mode==='walk'&&selected===r.id?'active':'')} onClick={()=>{setTour(false);enter(r.id);}}><span className="index">0{i+1}</span>{r.name}<ArrowUpRight/></Button>)}</nav><div className="reference-link"><Button variant="ghost" onClick={()=>setPanel(true)}><ImageIcon/>Photos & original plan<ArrowUpRight/></Button></div></aside>
 <div className="caption"><span className="eyebrow">{mode==='walk'?'INSIDE THE HOUSE':'OPEN ROOF · EXPLORATION VIEW'}</span><h2>{mode==='walk'?rooms.find(r=>r.id===selected)?.name:level?'The lower level':'The main level'}</h2><p>{mode==='walk'?'Drag to look · WASD or arrow keys to move':'Drag to orbit · scroll to zoom · right-drag to pan'}</p></div>
 {mode==='walk'&&<div className="walk-controls">{[['↶','left'],['↑','forward'],['↓','back'],['↷','right']].map(([label,dir])=><Button key={dir} variant="outline" aria-label={dir} onPointerDown={()=>viewer.current?.move(dir,true)} onPointerUp={()=>viewer.current?.move(dir,false)} onPointerLeave={()=>viewer.current?.move(dir,false)}>{label}</Button>)}</div>}
 {error&&<div role="alert" className="error">{error}<a href="/house/references/floor-plan.jpg" target="_blank" rel="noreferrer">Open original plan</a></div>}</section>
 <footer><span>● Exterior dimensions from the appraisal sketch</span><span>Interior layout, heights & furnishings are approximate</span><Button variant="link" onClick={()=>setPanel(true)}>About this model<ArrowUpRight/></Button></footer>
 {panel&&<div className="modal-backdrop" onClick={()=>setPanel(false)}><section className="reference-panel" role="dialog" aria-modal="true" aria-label="Model references" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setPanel(false);}}><Button autoFocus className="close" variant="outline" aria-label="Close references" onClick={()=>setPanel(false)}><X/></Button><p className="eyebrow">THE SOURCE MATERIAL</p><h2>Built from your house documents.</h2><p>The measured exterior outlines and room names come from the February 2026 appraisal. Interior walls, doors, windows, heights, alignment between levels, and furnishings are provisional. Colors and the wood ceiling are informed by the photos. This is an explorable first reconstruction, not a survey or a photographic scan.</p><div className="photo-grid">{['living','kitchen','dining'].map(name=><figure key={name}><img src={'/house/references/'+name+'.jpg'} alt={'Appraisal photo of '+name}/><figcaption>{name} · appraisal photo</figcaption></figure>)}</div><a href="/house/references/floor-plan.jpg" target="_blank" rel="noreferrer"><img className="plan" src="/house/references/floor-plan.jpg" alt="Appraisal sketch of both levels with exterior dimensions"/></a><p>The GLB export uses meters and imports into Blender. Your new photos will help refine this model.</p><Button onClick={()=>setPanel(false)}>Back to the house</Button></section></div>}</main>;
}
