export type PhotoReference = {
  id: string;
  title: string;
  roomId: string | null;
  date: string;
  confidence: 'High' | 'Likely' | 'Unplaced';
  evidence: string;
  furniture: string[];
  view?: { x: number; z: number; yaw: number; pitch: number; fov: number };
};

export const photoReferences: PhotoReference[] = [
  { id: 'living-wide', title: 'Living room · sofa wall', roomId: 'living', date: '2026-05-03', confidence: 'High', evidence: 'Bay window, vaulted wood ceiling and adjoining dining area identify the main living room.', furniture: ['White sofa', 'Slatted walnut coffee table', 'Natural woven rug', 'Cream accent chair', 'Tall arched mirrors'], view: { x: 15.5, z: 55.5, yaw: -2.25, pitch: -.12, fov: 75 } },
  { id: 'living-bay', title: 'Living room · bay seating', roomId: 'living', date: '2026-03-19', confidence: 'High', evidence: 'Three-part front window and entrance door match the front bay. This earlier view clearly shows the chaise.', furniture: ['White loveseat and chaise', 'Black leather lounge chair', 'Walnut coffee table'], view: { x: 24, z: 48.2, yaw: 2.9, pitch: -.12, fov: 75 } },
  { id: 'living-to-dining', title: 'Living toward dining', roomId: 'dining', date: '2026-06-22', confidence: 'High', evidence: 'Continuous wood ceiling, hall step, dining mirror and lounge chair connect the two spaces.', furniture: ['White slipcovered sofa', 'Black leather lounge chair and ottoman', 'Walnut dining table', 'Cream dining chairs', 'Arched dining mirror'], view: { x: 23.5, z: 56, yaw: .15, pitch: .05, fov: 78 } },
  { id: 'dining-bar', title: 'Dining room · bar and office doorway', roomId: 'dining', date: '2026-06-21', confidence: 'High', evidence: 'The doorway reveals the same navy cabinetry seen in the office photos; the hall opening is beside it.', furniture: ['Black rounded bar cabinet', 'Black leather lounge chair', 'Walnut dining table', 'Cream dining chairs'], view: { x: 22, z: 41.5, yaw: 1.25, pitch: .12, fov: 78 } },
  { id: 'kitchen-current', title: 'Kitchen · refrigerator and coffee station', roomId: 'kitchen', date: '2026-08-06', confidence: 'High', evidence: 'White cabinetry, brass hardware, scalloped backsplash and stainless refrigerator match the main kitchen.', furniture: ['Black espresso machine', 'Stainless French-door refrigerator', 'White pantry cabinetry'], view: { x: 14, z: 14, yaw: -.9, pitch: 0, fov: 72 } },
  { id: 'office-chair', title: 'Front office · chair and built-ins', roomId: 'front-bed', date: '2026-06-17', confidence: 'High', evidence: 'The listing plan marks a Murphy-bed wall in the front room. Navy built-ins and the sliding doorway link this room to the living area. Desk placement remains estimated.', furniture: ['Cream padded swivel chair', 'Navy built-in shelves', 'Walnut desk', 'Taupe curtains'], view: { x: 8.5, z: 51, yaw: 2.3, pitch: -.08, fov: 72 } },
  { id: 'bedroom-dressers', title: 'Bedroom · dressers and blue prints', roomId: null, date: '2026-06-20', confidence: 'Unplaced', evidence: 'The bedroom is recognizable, but the photos do not yet establish which bedroom on the plan. Furniture is recorded without assigning a position.', furniture: ['Two dark dressers with brass pulls', 'Two blue Van Gogh prints', 'Low bed with white bedding'] },
  { id: 'hallway', title: 'Main hall · toward the living room', roomId: 'hallway', date: '2026-03-30', confidence: 'High', evidence: 'The hallway terminates at the rounded black bar cabinet and front living area.', furniture: [] },
  { id: 'garden', title: 'Rear garden', roomId: 'deck', date: '2026-04-15', confidence: 'High', evidence: 'The newly recovered listing plan connects the kitchen to a rear deck and garden. Garden extent and planting positions are illustrative.', furniture: ['Yellow planter', 'Fern and bamboo planters'] },
  { id: 'measurement-sketch', title: 'Handwritten room measurements', roomId: null, date: '2026-03-19', confidence: 'Unplaced', evidence: 'The sketch labels two rooms “Lefty” and “Righty”. Their correspondence to the appraisal needs confirmation before using these dimensions.', furniture: [] },
  { id: 'interior-plan', title: 'Recovered listing floor plan · both apartments', roomId: null, date: '2026-02-21', confidence: 'High', evidence: 'Saved without a location tag, so it was missed in the first search. Unlike the appraisal outline, this plan shows interior walls, doors, closets, kitchen layouts, the office Murphy bed, rear deck and garden. Interior positions are traced and scaled approximately, not surveyed.', furniture: [] },
  { id: 'living-entry', title: 'Living room · entry and pitched ceiling', roomId: 'living', date: '2026-04-02', confidence: 'High', evidence: 'Shows both ceiling slopes, the front bay, white entry door and adjoining office opening. Used to replace the one-slope roof and locate the entry.', furniture: ['Bay loveseat and chaise', 'Slatted coffee table', 'Arched mirror'], view: {x:17,z:47.5,yaw:Math.PI,pitch:.12,fov:80} },
  { id: 'front-bay-current', title: 'Front bay · windows and door', roomId: 'living', date: '2026-04-01', confidence: 'High', evidence: 'A second front-facing view confirms the bay-seat arrangement and the door beside it. Window panes now occupy real openings rather than opaque walls.', furniture: ['White chaise', 'Walnut coffee table'], view: {x:18,z:49,yaw:Math.PI,pitch:0,fov:75} },
  { id: 'office-builtins-wall', title: 'Office · built-in wall before unpacking', roomId: 'front-bed', date: '2026-03-15', confidence: 'High', evidence: 'Moving-day view shows the navy cabinets beside the tall window. Combined with the plan’s Murphy-bed label, it establishes the cabinet wall orientation.', furniture: ['Navy Murphy-bed cabinetry', 'Brass handles'], view: {x:8,z:51,yaw:2.25,pitch:0,fov:80} },
  { id: 'kitchen-range', title: 'Kitchen · range and worktop', roomId: 'kitchen', date: '2026-08-16', confidence: 'High', evidence: 'Gas range, brass cabinet pulls and scalloped backsplash provide a closer material reference for the kitchen.', furniture: ['Stainless gas range', 'White worktop'] },
  { id: 'garden-from-deck', title: 'Deck · looking into the garden', roomId: 'deck', date: '2026-04-01', confidence: 'High', evidence: 'The deck railing, stairs and patio agree with the recovered plan. The exterior is included as a simplified extension, with heights still approximate.', furniture: ['Outdoor seating', 'Yellow planters'] },
  { id: 'bedroom-window', title: 'Bedroom · dark bedding and art ledge', roomId: null, date: '2026-03-25', confidence: 'Unplaced', evidence: 'A distinct bedroom with pale flooring, a single sash window and a low art ledge. Its exact room is not established, so it has not been assigned on the plan.', furniture: ['Dark upholstered bed', 'Art ledge'] },
  { id: 'exercise-room', title: 'Exercise room · wall trainer', roomId: null, date: '2026-06-24', confidence: 'Unplaced', evidence: 'A wall-mounted trainer, accessory rack and bench are visible, but this close view does not prove which room contains them.', furniture: ['Wall-mounted exercise machine', 'Workout bench'] },
  { id: 'hall-to-kitchen', title: 'Video reference · dining through hall to kitchen', roomId: 'hallway', date: '2026-08-30', confidence: 'High', evidence: 'A locally available video preview shows the continuous route from dining, over the hall threshold, toward the kitchen. This supports removing the guessed cross-wall.', furniture: ['Hall runner', 'Black bar cabinet'], view: {x:13.5,z:38,yaw:0,pitch:0,fov:65} },
  { id: 'office-sliding-door', title: 'Video reference · office sliding door', roomId: 'front-bed', date: '2026-05-15', confidence: 'High', evidence: 'The video preview shows a tall frosted panel in a wood frame beside the front entry. Added this opening and panel instead of the generic doorway.', furniture: ['Frosted wood-framed sliding door'], view: {x:15,z:49,yaw:Math.PI/2,pitch:0,fov:72} },
  { id: 'kitchen-sink', title: 'Video reference · sink and garden window', roomId: 'kitchen', date: '2026-05-10', confidence: 'High', evidence: 'Cooking-video preview establishes the sink beneath the garden-facing window and the adjacent range. Only the available still preview was used, not a reconstructed video scan.', furniture: ['White farmhouse sink', 'Gas range'] },
];

export const photoUrl = (id: string) => `/house/photos/${id}.jpg`;
